### ISSUE TITLE
getActivities returns 0 results

### ISSUE THREAD

**Issue by rph8** [adobe/adobeio-cna-core-target#4]
Using the sample code:
`const activities = await targetClient.getActivities({limit:5, offset:0})`
I always get 0 results:
`{ total: 0, offset: 0, limit: 5 }`

**Comment by sandeep-paliwal** [comment]
Hi @rph8 , Can you check there are any activities available? Like if you just call getActivities without any limit, do you get any response?

**Comment by meryllblanchet** [comment]
Hi @rph8 , did you have any chance to check the above? Thanks for your feedback!

**Comment by rph8** [comment]
Hey guys, this seems to be a silly mistake on my side: The testing environment seems to contain many offers but no activities. It did not expect the account to be configured in this way.

**Comment by meryllblanchet** [comment]
Thanks for the update @rph8 and never mind, this is confirming that the SDK behaved as expected ;-)
